services:
  slidev:
    image: tangramor/slidev:latest
    user: node
    ports:
      - "3030:3030"
    volumes:
      - .:/slidev
    environment:
      - NPM_MIRROR=https://registry.npmmirror.com
    stdin_open: true
    tty: true